### ISSUE TITLE
Fontawesome Free icons in HikaShop don't display correct

### ISSUE THREAD

**Issue by superknutsel** [TheStyleGuyzTeam/J4Atum-user-css#3]
If I'm correct the fontsize should be 900 by default for the free version.

A little test with this :
.hika_j4 a[class*="icon"] {
	font-weight: 900 !important;
}

Seems to have good results.
Anyone can confirm this ?

**Comment by RussW** [comment]
I'm assuming you are referring to the "Custom Quick Icons" extension mentioned in the JCM, not this as an Atum Template customisation. However, you are correct that the default FA font-weight is 900 as it is still if you use this CSS override.

Closed : not related to this project.

**Comment by superknutsel** [comment]
You assumed wrong.
Check line 89 and test to see for yourself.

**Comment by RussW** [comment]
No, the FA font-weight is not overridden from 900, when we override the text font-weight to 400.

So, no action required, no change required, no fix required. I still think you are looking at the wrong project regarding the font-weight as this particular project has absolutely no reference to Hika-Shop, or any other specific extension.
