### ISSUE TITLE
Rules not taken into account 

### ISSUE THREAD

**Issue by iorbita** [TheStyleGuyzTeam/J4Atum-user-css#4]
Hi, I also find some elements too big, the problem is it doesn’t work. I tried setting _!important_ rule with no results... there were any changes in the latest version of Joomla 4.1.0?

**Comment by RussW** [comment]
from from experience, I have had no issues with v4.10, however the location for the "user.css" has changed due to the introduction of "Child Templates" feature.

Place the user.css file in "media/templates/administrator/atum/css/" folder from v4.10 and above.

**Comment by iorbita** [comment]
it works... and it's really better, thanks!

**Comment by RussW** [comment]
Pleased to hear that you got it working ok and you are happy with the results - closing.
